name: .NET

on:
  push:
    branches: [ "dev-cypress-only" ]
    pull_request:
    branches: [ "main" ]
    types: [closed]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
  
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True

    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    # Add coverlet.collector nuget package to test project - 'dotnet add <xx.cspoj> package coverlet
    - name: Test 🧪
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
   
    - name: Process trx reports to obtain summary on (pull-requests)
      if: always()
      uses: im-open/process-dotnet-test-results@v2.1.3
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test Report (Summary)
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xUnit Test Run
        path: "**/coverage/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: clean cache
      run: npm cache clean --force
    - name: npm install
      run: npm install
      working-directory: ./simplecrmweb
    - name: npm ci
      run: npm ci
      working-directory: ./simplecrmweb
        
    - name: Run Component tests 🧪
      uses: cypress-io/github-action@v4
      with:
        working-directory: ./simplecrmweb
        # we have already installed everything
        install: true
        # to run component tests we need to use "component: true"
        component: true
        browser: chrome

    # - name: Cypress Component Test Artifacts (inital temporary configuration)
    #       # after the test run completes
    #       # store videos and any screenshots
    #       # NOTE: screenshots will be generated only if E2E test failed
    #       # thus we store screenshots only on failures
    #       # Alternative: create and commit an empty cypress/screenshots folder
    #       # to always have something to upload
    #   uses: actions/upload-artifact@v2
    #   #if: failure()fix 4
    #   #with:
    #   #      working-directory: ./simplecrmweb
    #   #     name: cypress-screenshots
    #   #     path: cypress/screenshots
    #   # Test run video was always captured, so this action uses "always()" condition
    #   if: always()
    #   with:
    #         github-token: ${{ secrets.GITHUB_TOKEN }}
    #         result-file: .\simplecrmweb\result.json
      - name: Start web app 📡
        run: npm start
        working-directory: ./simplecrmweb        
      - name: Start E2E tests 🧪 
        run: npx cypress run --browser chrome
        working-directory: ./simplecrmweb        

