name: .NET

on:
  push:
    branches: [ "dev-cypress-only" ]
    pull_request:
    branches: [ "main" ]
    types: [closed]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
  
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        include-prerelease: True

    - name: Install Azurite
      id: azuright
      uses: potatoqualitee/azuright@v1.1

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    # Add coverlet.collector nuget package to test project - 'dotnet add <xx.cspoj> package coverlet
    - name: Test 🧪
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
   
    - name: Process trx reports to obtain summary on (pull-requests)
      if: always()
      uses: im-open/process-dotnet-test-results@v2.1.3
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Test Report (Summary)
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xUnit Test Run
        path: "**/coverage/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: clean cache
      run: npm cache clean --force
    - name: npm install
      run: npm install
      working-directory: ./simplecrmweb
    - name: npm ci
      run: npm ci
      working-directory: ./simplecrmweb
    
      
    - name: Run Jest unit tests
      run: npm test --if-present
      working-directory: ./simplecrmweb
      
    - name: Jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      id: coverage
      with:
           output: report-markdown
           working-directory: ./simplecrmweb
    - name: Jest coverage report upload to github
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: ${{ steps.coverage.outputs.report }}
        
    - name: Jest Tests (PASSED) results ✅
      if: ${{ success() }}
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

    - name: Jest Tests (FAILED) 🚨
      if: ${{ failure() }}
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'  
        
    - name: Run Component tests 🧪
      uses: cypress-io/github-action@v4
      with:
        working-directory: ./simplecrmweb
        # we have already installed everything
        install: true
        # to run component tests we need to use "component: true"
        component: true
        browser: chrome
    - name: Cypress Component Test Artifacts (inital temporary configuration)
          # after the test run completes
          # store videos and any screenshots
          # NOTE: screenshots will be generated only if E2E test failed
          # thus we store screenshots only on failures
          # Alternative: create and commit an empty cypress/screenshots folder
          # to always have something to upload
      uses: actions/upload-artifact@v2
      #if: failure()
      #with:
      #      working-directory: ./simplecrmweb
      #     name: cypress-screenshots
      #     path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      if: always()
      with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            result-file: .\simplecrmweb\result.json
      
#sepearate here for Jest coverage
  coverage:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              id: coverage
              with:
                  output: report-markdown
                  working-directory: ./simplecrmweb
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: ${{ steps.coverage.outputs.report }}
            - name: ReportGenerator
              uses: danielpalme/ReportGenerator-GitHub-Action@5.1.4
              with:
                reports: 'coverage/*/coverage.cobertura.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
                targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
                reporttypes: 'HtmlInline;Cobertura' # The output formats and scope (separated by semicolon)

            - name: Upload coverage report artifact
              uses: actions/upload-artifact@v2.2.3
              with:
                name: CoverageReport # Artifact name        
                path: coveragereport # Directory containing files to upload  
    
            - name: Code Coverage Summary Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                filename: coveragereport/Cobertura.xml
                badge: true
                format: 'markdown'
                output: 'both'

            - name: Add Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: github.event_name == 'pull_request'
              with:
                recreate: true
                path: code-coverage-results.md

            - name: Write to Job Summary
              run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY          
       
    